channels:
    Alexa 488 2: Ch3_2
    Alexa 488 4: Ch3_4
    Alexa 568 2: Ch4_2
    Alexa 568 4: Ch4_4
    Alexa 647 2: Ch5_2
    Alexa 647 4: Ch5_4
    Pacific Blue 2: Ch6_2
    Pacific Blue 4: Ch6_4
    Brightfield -2: Brightfield_-2
    Brightfield 0: Brightfield_0
    Brightfield 2: Brightfield_2
    Brightfield 4: Brightfield_4
    Brightfield 6: Brightfield_6
    Brightfield 8: Brightfield_8
    Brightfield 10: Brightfield_10
    Brightfield 12: Brightfield_12
    Brightfield 14: Brightfield_14
    Digital Phase Contrast nr: PhaseContrast_0
metadata:
    Row: Row
    Col: Col
    FieldID: FieldID
    PlaneID: PlaneID
    ChannelID: ChannelID
    ChannelName: ChannelName
    TimepointID: TimepointID
    AbsTime: AbsTime
