channels:
    Alexa 488: Ch3
    Alexa 568: Ch4
    Alexa 647: Ch5
    DAPI: Ch6
    Brightfield: Brightfield
    Digital Phase Contrast nr: PhaseContrast
metadata:
    Row: Row
    Col: Col
    FieldID: FieldID
    PlaneID: PlaneID
    ChannelID: ChannelID
    ChannelName: ChannelName
    TimepointID: TimepointID
    AbsTime: AbsTime
    ExposureTime: ExposureTime
